export default [
    {
      id: 1,
      brand: "Jellycat",
      citizenship: "Beside Grace",
      type: "Finnegan Frog",
      nickname: "Steve",
      size: "9.1in x 2.8in x 2.8in",
      photo: "FinneganFrog.jpg",
      birthdate: "Oct. 20, 2024",
      address: "Left Corner of Grace's Desk",
      serial_num: "JCINC6277IL-FIN3FRN",
      active: true,
      user_id: 1
    },
    {
      id: 2,
      brand: "Rellycat",
      citizenship: "Canada",
      type: "Cat",
      nickname: "Tigger",
      size: "16 pounds",
      photo: "ReallyCat.jpg",
      birthdate: "August 28, 2023",
      address: "Grace's Home",
      serial_num: "AUG28-2023-TIGGER",
      active: true,
      user_id: 2
    },
    {
      id: 3,
      brand: "Ikea",
      citizenship: "Ocean",
      type: "BLÅHAJ",
      nickname: "Sasha",
      size: "100cm long",
      photo: "IkeaShark.jpg",
      birthdate: "Sept. 2, 2023",
      address: "On the Couch",
      serial_num: "903.735.90-PA 14632",
      active: true,
      user_id: 3
    },
    {
      id: 4,
      brand: "Jellycat",
      citizenship: "Woodland",
      type: "Bartholomew Bear",
      nickname: "Bear",
      size: "Really Big",
      photo: "BartholomewBear.jpg",
      birthdate: "Sept. 24, 2024",
      address: "On the Bed",
      serial_num: "JCINC6300IF-BARRB1BR",
      active: true,
      user_id: 4
    },
    {
      id: 5,
      brand: "Jellycat",
      citizenship: "Woodland",
      type: "Bashful Fox",
      nickname: "Fox",
      size: "Giant or Really Really Big",
      photo: "GiantBashfulFox.jpg",
      birthdate: "Aug. 17, 2024",
      address: "Penthouse on The Shelf",
      serial_num: "",
      active: true,
      user_id: 5
    }
]