export default [
  {
    id: 1,
    brand: "Jellycat",
    citizenship: "Beside Grace",
    type: "Finnegan Frog",
    nickname: "Steve",
    size: "9.1in x 2.8in x 2.8in",
    photo: "FinneganFrog.jpg",
    birthdate: "Oct. 20, 2024",
    address: "Left Corner of Grace's Desk",
    serial_num: "JCINC6277IL-FIN3FRN",
    active: true,
  },
  {
    id: 2,
    brand: "Reallycat",
    citizenship: "Canada",
    type: "Cat",
    nickname: "Tigger",
    size: "16 pounds",
    photo: 'ReallyCat.jpg',
    birthdate: "August 28, 2023",
    address: "Grace's Home",
    serial_num: "AUG28-2023-TIGGER",
    active: true,
  },
  {
    id: 3,
    brand: "Ikea",
    citizenship: "Ocean",
    type: "BLÅHAJ",
    nickname: "Sasha",
    size: "100cm long",
    photo: "IkeaShark.jpg",
    birthdate: "Sept. 2, 2023",
    address: "On the Couch",
    serial_num: "903.735.90-PA 14632",
    active: true,
  },
  {
    id: 4,
    brand: "Jellycat",
    citizenship: "Woodland",
    type: "Bartholomew Bear",
    nickname: "Bear",
    size: "Really Big",
    photo: "BartholomewBear.jpg",
    birthdate: "Sept. 24, 2024",
    address: "On the Bed",
    serial_num: "JCINC6300IF-BARRB1BR",
    active: true,
  },
  {
    id: 5,
    brand: "Jellycat",
    citizenship: "Woodland",
    type: "Bashful Fox",
    nickname: "Fox",
    size: "Giant or Really Really Big",
    photo: "GiantBashfulFox.jpg",
    birthdate: "Aug. 17, 2024",
    address: "Penthouse on The Shelf",
    serial_num: "xxx",
    active: true
  },
  {
    id:6,
    brand: "Jellycat",
    citizenship: "Heaven",
    type: "Mammoth",
    nickname: "Dumbo",
    size: "large",
    photo: "N/A",
    birthdate: "June 2, 2023",
    address: "Grace's heart",
    serial_num: "xxx",
    active: false
  }
]

//npx knex seed:run    to update data